services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: >
      bash -c 'if [ "$DEBUG" = "1" ]; then
                  python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest;
               else
                  pytest;
               fi'
    depends_on:
      - test_db
    volumes:
      - .:/app
    ports:
      - 5678:5678
    environment:
      - DB_USER=test_foodics
      - DB_PASSWORD=test_foodics
      - DB_NAME=test_foodics_db
      - DB_HOST=test_db
      - DB_PORT=5432
      - SENDGRID_API_KEY=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
      - FROM_EMAIL=abdelrahmen.ayman10@gmail.com
      - MERCHANT_EMAIL=abdelrahmenayman7@gmail.com

  test_db:
    image: postgres:17
    tmpfs: 
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_foodics
      - POSTGRES_PASSWORD=test_foodics
      - POSTGRES_DB=test_foodics_db